# Generated by Django 5.2.17 on 2026-08-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
